# Generated by Django 5.0.8 on 2026-06-27 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money (Orange, MTN, Wave)'), ('CARD', 'Carte Bancaire'), ('CASH', 'Espèces à la livraison')], max_length=20, verbose_name='Type de fournisseur')),
                ('provider_name', models.CharField(max_length=50, verbose_name='Nom du service')),
                ('account_identifier', models.CharField(max_length=100, verbose_name='Identifiant du compte / Numéro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_catalogs', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Marchand')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_catalogs', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'PaymentMethod',
                'verbose_name_plural': 'PaymentMethods',
                'ordering': ['-created_at'],
            },
        ),
    ]
