# Generated by Django 5.0.8 on 2026-06-27 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'OTP de réinitialisation',
                'verbose_name_plural': 'OTP de réinitialisation',
                'ordering': ['-created_at'],
            },
        ),
    ]
